[package]
name = "gpmf-rust"
version = "0.1.0"
authors = ["Joe Harrison <joe@sigwinch.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.15"
encoding_rs = "0.8.24"
nom = "5.1.2"